### ISSUE TITLE
Apigee X integration for apigeetool

### ISSUE THREAD

**Issue by fabien38** [apigee/apigeetool-node#203]
apigeetool is not working with the embedded version of apigee inside google because the uri is not using the right paths for organizations

by default in all js file you use 

  var uri = util.format('%s/v1/          **o**                               /%s/apis?action=import&validate=false&name=%s',
                        opts.baseuri, opts.organization, opts.api);

to build the uri whereas it should be 
  var uri = util.format('%s/v1/      **organizations**                 /%s/apis?action=import&validate=false&name=%s',
                        opts.baseuri, opts.organization, opts.api);

so replace "o" with "organizations"
and it is not changing the way it works with apigee edge as apigee edge uses this organizations path as well

**Comment by DinoChiesa** [comment]
Ack.  I know it's been more than a year since you filed this issue. 
You're right that apigeetool won't work with X/hybrid. The shape of the URL is one problem. There are others.
- the API for proxy import/upload is different. 
- the responses for some of the APIs are different
- There are new features in X not supported by apigeetool
- the KVM API is very different
- there are features in Edge supported by apigeetool but not available in X/hybrid

There may be other things I am not thinking of right now. So there would be a significant amount of work to enhance apigeetool to work with X/hybrid. 
At this time we do not have a resource plan to perform that work. 

I'll keep the ticket open for now. We may re-prioritize and get some resource on this.

**Comment by DinoChiesa** [comment]
We will not update apigeetool for use with X and hybrid. 
You should use https://github.com/apigee/apigeecli/blob/main/docs/apigeecli.md with Apigee X and hybrid. 

Closing this out .
